openapi: 3.0.3
info:
  title: API Adoptions
  version: 1.0.0
  description: Gestión para las Adopciones de las Mascotas.

tags:
  - name: Adoptions
    description: Gestión de Adopciones.

paths:
  /adoptions:
    get:
      summary: Obtiene Todas las Adopciones.
      tags: [Adoptions]
      responses:
        "200":
          description: Lista de Todas las Adopciones.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Adoption"

  /adoptions/{uid}/{pid}:
    post:
      summary: Registra una Nueva Adopción.
      tags: [Adoptions]
      parameters:
        - name: uid
          in: path
          required: true
          schema:
            type: string
          description: ID del Usuario.
        - name: pid
          in: path
          required: true
          schema:
            type: string
          description: ID de la Mascota.
      responses:
        "200":
          description: Adopción Registrada Correctamente!
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Adoption"
        "400":
          description: Mascota ya Adoptada o Error de Validación.
        "404":
          description: Usuario o Mascota no encontrados.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Error Interno del Servidor.

  /adoptions/{aid}:
    get:
      summary: Obtiene una Adopción por ID.
      tags: [Adoptions]
      parameters:
        - name: aid
          in: path
          required: true
          schema:
            type: string
          description: ID de la Adopción.
      responses:
        "200":
          description: Adopción Encontrada.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Adoption"
        "400":
          description: ID inválido.
        "404":
          description: La Adopción no fue Encontrada en la Base de Datos...
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Error Interno del Servidor.

    put:
      summary: Actualiza una Adopción por ID.
      tags: [Adoptions]
      parameters:
        - name: aid
          in: path
          required: true
          schema:
            type: string
          description: ID de la Adopción a Actualizar.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                owner:
                  type: string
                pet:
                  type: string
      responses:
        "200":
          description: Adopción Actualizada Correctamente.
        "404":
          description: La Adopción no fue encontrada.
        "500":
          description: Error Interno del Servidor.

    delete:
      summary: Elimina una Adopción por ID.
      tags: [Adoptions]
      parameters:
        - name: aid
          in: path
          required: true
          schema:
            type: string
          description: ID de la Adopción a Eliminar.
      responses:
        "200":
          description: Adopción Eliminada Correctamente.
        "404":
          description: La Adopción no se encontró.
        "500":
          description: Error Interno del Servidor.

components:
  schemas:
    Adoption:
      type: object
      properties:
        id:
          type: string
          description: ID de la Adopción.
          example: "64a1f1e3b9e2f8b1a2c3d4e5"
        userId:
          type: string
          description: ID del Usuario que Adopta a la Mascota.
          example: "64a1f0a7b9e2f8b1a2c3d4d1"
        petId:
          type: string
          description: ID de la Mascota Adoptada.
          example: "641f2b1e0c123456789abcd0"
        adoptionDate:
          type: string
          format: date-time
          description: Fecha y Hora de la Adopción.
          example: "2024-05-15T14:30:00Z"

    Error:
      type: object
      properties:
        message:
          type: string
          example: "La Adopción no fue Encontrada..."
