openapi: 3.0.3
info:
  title: API Sessions
  version: 1.0.0
  description: Gestión para la Autenticación y Sesiones de Usuarios.

tags:
  - name: Sessions
    description: Gestión de Sesiones de Usuarios.

paths:
  /sessions/register:
    post:
      summary: Registra a un Nuevo Usuario.
      tags:
        - Sessions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  example: user@example.com
                password:
                  type: string
                  format: password
                  example: strongPassword123
      responses:
        "201":
          description: Usuario Registrado Éxitosamente.
        "400":
          description: Datos Incompletos o Inválidos.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "409":
          description: El Usuario ya Existe.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Error Interno del Servidor.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /sessions/login:
    post:
      summary: Inicia Sesión con Email y Contraseña.
      tags:
        - Sessions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  example: user@example.com
                password:
                  type: string
                  format: password
                  example: strongPassword123
      responses:
        "200":
          description: Usuario Autenticado / Logueado Correctamente.
        "401":
          description: Credenciales Inválidas.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Error Interno del Servidor.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /sessions/current:
    get:
      summary: Obtiene la Sesión del Usuario Autenticado / Logueado.
      tags:
        - Sessions
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Sesión Activa del Usuario.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserSession"
        "401":
          description: Usuario No Autenticado.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Error Interno del Servidor.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /sessions/unprotectedLogin:
    get:
      summary: Ruta de Login Sin Protección (Sólo para Pruebas...)
      tags:
        - Sessions
      responses:
        "200":
          description: Usuario Autenticado Sin Protección.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserSession"

  /sessions/unprotectedCurrent:
    get:
      summary: Devuelve la Sesión Sin Validación de Token (Sólo para Pruebas...)
      tags:
        - Sessions
      responses:
        "200":
          description: Sesión Actual Sin Protección.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserSession"

  /sessions/logout:
    post:
      summary: Cierra la Sesión del Usuario.
      tags:
        - Sessions
      responses:
        "200":
          description: Sesión Cerrada Correctamente.
        "400":
          description: No Hay Sesión Activa.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Error Interno del Servidor.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    UserSession:
      type: object
      properties:
        id:
          type: string
          description: ID del Usuario.
          example: 64a1f1e3b9e2f8b1a2c3d4e5
        email:
          type: string
          format: email
          example: user@example.com
        roles:
          type: array
          items:
            type: string
          description: Roles del Usuario.
          example: ["user", "admin"]

    Error:
      type: object
      properties:
        message:
          type: string
          description: Descripción del Error.
          example: Credenciales Inválidas.
